name: nf-inspect

channels:
    - conda-forge
    - bioconda

dependencies:
    - python=3.11
    - pip
    - bioconda::fastqc
    - pip:
        - 'cutadapt>=4.0'
        - 'carabiner-tools[mpl,pd]==0.0.3.post1'
        - 'cutadapt==5.0'
        - 'multiqc==1.21'
        - 'umi-tools==1.1.6'