name: nf-inspect

channels:
    - conda-forge
    - bioconda

dependencies:
    - python
    - pip
    - cutadapt
    - fastqc
    - multiqc
    - openjdk
    - umi_tools
    - pip:
        - matplotlib
        - numpy
        - pandas