name: nf-inspect

channels:
    - defaults
    - bioconda

dependencies:
    - python=3.10
    - pip
    - bioconda::fastqc
    - umi_tools
    - pip:
        - cutadapt
        - matplotlib
        - multiqc
        - numpy
        - pandas