name: nf-inspect

channels:
    - conda-forge
    - bioconda

dependencies:
    - python>=3.8
    - pip
    - bioconda::fastqc
    - umi_tools>=1.0
    - pip:
        - 'cutadapt>=4.0'
        - matplotlib
        - 'multiqc>=1.21'
        - numpy
        - pandas