name: nf-inspect

channels:
    - conda-forge
    - bioconda

dependencies:
    - python=3.11
    - pip
    - bioconda::fastqc
    - pip:
        - 'cutadapt>=4.0'
        - matplotlib
        - 'multiqc>=1.21'
        - numpy
        - 'pandas>=2.1.2'
        - 'umi_tools>=1.0'