name: nf-inspect

channels:
    - conda-forge
    - bioconda

dependencies:
    - python
    - pip
    - fastqc
    - umi_tools
    - pip:
        - cutadapt
        - matplotlib
        - multiqc
        - numpy
        - pandas